version: '3.7'

networks:
  dbnet:
    external: true
    name: dbnet

services:
  ecoshop:
    image: 0sko/simple-flask-app-preproduction:latest
    container_name: ecoshop
    ports:
      - "5000:5000"
    networks:
      - dbnet